## NX LAYOUT CONSTRAINTS 16-BIT PUF 001 -- STREAMLINED NET DELAYS & MINIMUM D-LATCH RANGE

## Clock signal
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk]
#set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk_lo]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
#create_clock -period 1000.000 -name sys_clk_pin -waveform {0.000 500.000} -add [get_ports clk_lo]


## Button signals
#set_property PACKAGE_PIN C12 [get_ports reset]
#set_property IOSTANDARD LVCMOS33 [get_ports reset]
#set_property PACKAGE_PIN M18 [get_ports START]
#set_property IOSTANDARD LVCMOS33 [get_ports START]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets StartN_IBUF]
set_property CLOCK_BUFFER_TYPE BUFG [get_ports reset]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets reset_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets START_IBUF]

##Switches
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports reset]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports START]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports {addr[0]}]
set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports rst_div]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports selclk]


# LED signals
#set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[0]}]
#set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[1]}]
#set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[2]}]
#set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[3]}]
#set_property -dict {PACKAGE_PIN B14 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[4]}]
#set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[5]}]
#set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[6]}]
#set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[7]}]
#set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[8]}]
#set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[9]}]
#set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[10]}]
#set_property -dict {PACKAGE_PIN D12 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[11]}]
#set_property -dict {PACKAGE_PIN D13 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[12]}]
#set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[13]}]
#set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[14]}]
#set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[15]}]

##Pmod Header JB

#set_property -dict { PACKAGE_PIN D14   IOSTANDARD LVCMOS33 } [get_ports { JB[1] }]; #IO_L1P_T0_AD0P_15 Sch=jb[1]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports clkout1]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports clkout2]
#set_property -dict { PACKAGE_PIN H14   IOSTANDARD LVCMOS33 } [get_ports { JB[4] }]; #IO_L15P_T2_DQS_15 Sch=jb[4]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33} [get_ports clkpuf]
#set_property -dict { PACKAGE_PIN F13   IOSTANDARD LVCMOS33 } [get_ports { JB[8] }]; #IO_L5P_T0_AD9P_15 Sch=jb[8]
#set_property -dict { PACKAGE_PIN G13   IOSTANDARD LVCMOS33 } [get_ports { JB[9] }]; #IO_0_15 Sch=jb[9]
#set_property -dict { PACKAGE_PIN H16   IOSTANDARD LVCMOS33 } [get_ports { JB[10] }]; #IO_L13P_T2_MRCC_15 Sch=jb[10]


##Pmod Header JC
set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[0]}]
set_property -dict {PACKAGE_PIN F6 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[1]}]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[2]}]
set_property -dict {PACKAGE_PIN G6 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[3]}]
set_property -dict {PACKAGE_PIN E7 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[4]}]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[5]}]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[6]}]
set_property -dict {PACKAGE_PIN E6 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[7]}]

##Pmod Header JD
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[8]}]
set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[9]}]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[10]}]
set_property -dict {PACKAGE_PIN G3 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[11]}]
set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[12]}]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[13]}]
set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[14]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[15]}]


#set_property BEL B5LUT [get_cells dl0/OUT_OBUF_inst_i_1]
#set_property LOC SLICE_X6Y100 [get_cells dl0/OUT_OBUF_inst_i_1]

#set_property BEL BFF [get_cells dl0/Q_reg]
#set_property LOC SLICE_X3Y100 [get_cells dl0/Q_reg]

#set_property BEL B5LUT [get_cells dl1/Q_reg_i_1]
#set_property LOC SLICE_X13Y46 [get_cells dl1/Q_reg_i_1]





#set_property BEL BFF [get_cells dl1/Q_reg]
#set_property LOC SLICE_X13Y46 [get_cells dl1/Q_reg]
#create_clock -period 100.000 -name DBG_CLK -waveform {0.000 50.000}# -add [get_ports {dbg_hub/inst/BSCANID.u_xsdbm_id/SWITCH_N_EXT_BSCAN.bscan_inst/SERIES7_BSCAN.bscan_inst/TCK} ]


#set_property DRIVE 12 [get_ports {OUT_reg[3]}]

#set_property BEL D6LUT [get_cells i_25]
#set_property LOC SLICE_X14Y89 [get_cells i_25]

set_property BEL A6LUT [get_cells {puf_loop[1].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X29Y197 [get_cells {puf_loop[1].puf_inst/dl0/OUT_INST_0}]
set_property BEL B6LUT [get_cells {puf_loop[1].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X29Y197 [get_cells {puf_loop[1].puf_inst/dl1/Q_reg_i_1}]
set_property BEL BFF [get_cells {puf_loop[2].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X29Y196 [get_cells {puf_loop[2].puf_inst/dl1/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[2].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X29Y196 [get_cells {puf_loop[2].puf_inst/dl0/OUT_INST_0}]
set_property BEL BFF [get_cells {puf_loop[1].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X29Y197 [get_cells {puf_loop[1].puf_inst/dl0/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[1].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X29Y197 [get_cells {puf_loop[1].puf_inst/dl1/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[2].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X29Y196 [get_cells {puf_loop[2].puf_inst/dl0/Q_reg}]
set_property BEL B6LUT [get_cells {puf_loop[2].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X29Y196 [get_cells {puf_loop[2].puf_inst/dl1/Q_reg_i_1}]

set_property BEL B6LUT [get_cells {puf_loop[0].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X29Y198 [get_cells {puf_loop[0].puf_inst/dl1/Q_reg_i_1}]
set_property BEL A6LUT [get_cells {puf_loop[3].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X29Y195 [get_cells {puf_loop[3].puf_inst/dl1/Q_reg_i_1}]

set_property BEL B6LUT [get_cells {puf_loop[3].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X29Y195 [get_cells {puf_loop[3].puf_inst/dl0/OUT_INST_0}]
set_property BEL BFF [get_cells {puf_loop[3].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X29Y195 [get_cells {puf_loop[3].puf_inst/dl0/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[3].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X29Y195 [get_cells {puf_loop[3].puf_inst/dl1/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[0].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X29Y198 [get_cells {puf_loop[0].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[0].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X29Y198 [get_cells {puf_loop[0].puf_inst/dl0/Q_reg}]
set_property BEL BFF [get_cells {puf_loop[0].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X29Y198 [get_cells {puf_loop[0].puf_inst/dl1/Q_reg}]

set_property BEL A6LUT [get_cells {puf_loop[4].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X49Y178 [get_cells {puf_loop[4].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[4].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X49Y178 [get_cells {puf_loop[4].puf_inst/dl0/Q_reg}]
set_property BEL BFF [get_cells {puf_loop[4].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X49Y178 [get_cells {puf_loop[4].puf_inst/dl1/Q_reg}]
set_property BEL B6LUT [get_cells {puf_loop[4].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X49Y178 [get_cells {puf_loop[4].puf_inst/dl1/Q_reg_i_1}]
set_property BEL A6LUT [get_cells {puf_loop[5].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X49Y177 [get_cells {puf_loop[5].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[5].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X49Y177 [get_cells {puf_loop[5].puf_inst/dl0/Q_reg}]
set_property BEL BFF [get_cells {puf_loop[5].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X49Y177 [get_cells {puf_loop[5].puf_inst/dl1/Q_reg}]
set_property BEL B6LUT [get_cells {puf_loop[5].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X49Y177 [get_cells {puf_loop[5].puf_inst/dl1/Q_reg_i_1}]
set_property BEL B6LUT [get_cells {puf_loop[6].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X49Y176 [get_cells {puf_loop[6].puf_inst/dl0/OUT_INST_0}]
set_property BEL BFF [get_cells {puf_loop[6].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X49Y176 [get_cells {puf_loop[6].puf_inst/dl0/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[6].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X49Y176 [get_cells {puf_loop[6].puf_inst/dl1/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[6].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X49Y176 [get_cells {puf_loop[6].puf_inst/dl1/Q_reg_i_1}]
set_property BEL C6LUT [get_cells {puf_loop[7].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X49Y175 [get_cells {puf_loop[7].puf_inst/dl0/OUT_INST_0}]
set_property BEL CFF [get_cells {puf_loop[7].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X49Y175 [get_cells {puf_loop[7].puf_inst/dl0/Q_reg}]
set_property BEL DFF [get_cells {puf_loop[7].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X49Y175 [get_cells {puf_loop[7].puf_inst/dl1/Q_reg}]
set_property BEL D6LUT [get_cells {puf_loop[7].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X49Y175 [get_cells {puf_loop[7].puf_inst/dl1/Q_reg_i_1}]
set_property BEL A6LUT [get_cells {puf_loop[11].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X12Y175 [get_cells {puf_loop[11].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[11].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X12Y175 [get_cells {puf_loop[11].puf_inst/dl0/Q_reg}]
set_property BEL BFF [get_cells {puf_loop[11].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X12Y175 [get_cells {puf_loop[11].puf_inst/dl1/Q_reg}]
set_property BEL B6LUT [get_cells {puf_loop[11].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X12Y175 [get_cells {puf_loop[11].puf_inst/dl1/Q_reg_i_1}]
set_property BEL A6LUT [get_cells {puf_loop[9].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X12Y177 [get_cells {puf_loop[9].puf_inst/dl1/Q_reg_i_1}]
set_property BEL B6LUT [get_cells {puf_loop[9].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X12Y177 [get_cells {puf_loop[9].puf_inst/dl0/OUT_INST_0}]
set_property BEL BFF [get_cells {puf_loop[9].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X12Y177 [get_cells {puf_loop[9].puf_inst/dl0/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[9].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X12Y177 [get_cells {puf_loop[9].puf_inst/dl1/Q_reg}]
set_property BEL B6LUT [get_cells {puf_loop[10].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X12Y176 [get_cells {puf_loop[10].puf_inst/dl1/Q_reg_i_1}]
set_property BEL A6LUT [get_cells {puf_loop[10].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X12Y176 [get_cells {puf_loop[10].puf_inst/dl0/OUT_INST_0}]
set_property BEL BFF [get_cells {puf_loop[10].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X12Y176 [get_cells {puf_loop[10].puf_inst/dl0/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[10].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X12Y176 [get_cells {puf_loop[10].puf_inst/dl1/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[8].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X12Y178 [get_cells {puf_loop[8].puf_inst/dl0/OUT_INST_0}]
set_property BEL BFF [get_cells {puf_loop[8].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X12Y178 [get_cells {puf_loop[8].puf_inst/dl0/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[8].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X12Y178 [get_cells {puf_loop[8].puf_inst/dl1/Q_reg}]
set_property BEL B6LUT [get_cells {puf_loop[8].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X12Y178 [get_cells {puf_loop[8].puf_inst/dl1/Q_reg_i_1}]
set_property BEL A6LUT [get_cells {puf_loop[15].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X30Y150 [get_cells {puf_loop[15].puf_inst/dl0/OUT_INST_0}]
set_property BEL A6LUT [get_cells {puf_loop[14].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X30Y151 [get_cells {puf_loop[14].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[14].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X30Y151 [get_cells {puf_loop[14].puf_inst/dl0/Q_reg}]
set_property BEL BFF [get_cells {puf_loop[14].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X30Y151 [get_cells {puf_loop[14].puf_inst/dl1/Q_reg}]
set_property BEL B6LUT [get_cells {puf_loop[14].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X30Y151 [get_cells {puf_loop[14].puf_inst/dl1/Q_reg_i_1}]
set_property BEL AFF [get_cells {puf_loop[15].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X30Y150 [get_cells {puf_loop[15].puf_inst/dl0/Q_reg}]
set_property BEL BFF [get_cells {puf_loop[15].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X30Y150 [get_cells {puf_loop[15].puf_inst/dl1/Q_reg}]
set_property BEL B6LUT [get_cells {puf_loop[15].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X30Y150 [get_cells {puf_loop[15].puf_inst/dl1/Q_reg_i_1}]
set_property BEL A6LUT [get_cells {puf_loop[13].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X30Y152 [get_cells {puf_loop[13].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[13].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X30Y152 [get_cells {puf_loop[13].puf_inst/dl0/Q_reg}]
set_property BEL BFF [get_cells {puf_loop[13].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X30Y152 [get_cells {puf_loop[13].puf_inst/dl1/Q_reg}]
set_property BEL B6LUT [get_cells {puf_loop[13].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X30Y152 [get_cells {puf_loop[13].puf_inst/dl1/Q_reg_i_1}]
set_property BEL C6LUT [get_cells {puf_loop[12].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X30Y153 [get_cells {puf_loop[12].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[12].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X30Y153 [get_cells {puf_loop[12].puf_inst/dl0/Q_reg}]
set_property BEL BFF [get_cells {puf_loop[12].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X30Y153 [get_cells {puf_loop[12].puf_inst/dl1/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[12].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X30Y153 [get_cells {puf_loop[12].puf_inst/dl1/Q_reg_i_1}]

set_property BEL CFF [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/uuid_stamp_reg[28]}]
set_property LOC SLICE_X45Y81 [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/uuid_stamp_reg[28]}]
set_property BEL B6LUT [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/reg_do[14]_i_2}]
set_property LOC SLICE_X44Y81 [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/reg_do[14]_i_2}]
set_property BEL DFF [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/uuid_stamp_reg[34]}]
set_property LOC SLICE_X45Y82 [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/uuid_stamp_reg[34]}]
set_property BEL AFF [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/uuid_stamp_reg[18]}]
set_property LOC SLICE_X44Y82 [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/uuid_stamp_reg[18]}]
set_property BEL BFF [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/uuid_stamp_reg[46]}]
set_property LOC SLICE_X44Y81 [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/uuid_stamp_reg[46]}]
set_property BEL A6LUT [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/reg_do[13]_i_3}]
set_property LOC SLICE_X44Y82 [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/reg_do[13]_i_3}]
set_property BEL A6LUT [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/reg_do[12]_i_2}]
set_property LOC SLICE_X44Y81 [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/reg_do[12]_i_2}]

set_property BEL D6LUT [get_cells {OUT_reg[0]_i_1}]
set_property LOC SLICE_X6Y160 [get_cells {OUT_reg[0]_i_1}]
set_property BEL C6LUT [get_cells {OUT_reg[1]_i_1}]
set_property LOC SLICE_X6Y160 [get_cells {OUT_reg[1]_i_1}]
set_property BEL B6LUT [get_cells {OUT_reg[2]_i_1}]
set_property LOC SLICE_X6Y160 [get_cells {OUT_reg[2]_i_1}]
set_property BEL A6LUT [get_cells {OUT_reg[3]_i_1}]
set_property LOC SLICE_X6Y160 [get_cells {OUT_reg[3]_i_1}]
set_property BEL D6LUT [get_cells {OUT_reg[4]_i_1}]
set_property LOC SLICE_X6Y159 [get_cells {OUT_reg[4]_i_1}]
set_property BEL C6LUT [get_cells {OUT_reg[5]_i_1}]
set_property LOC SLICE_X6Y159 [get_cells {OUT_reg[5]_i_1}]
set_property BEL B6LUT [get_cells {OUT_reg[6]_i_1}]
set_property LOC SLICE_X6Y159 [get_cells {OUT_reg[6]_i_1}]
set_property BEL A6LUT [get_cells {OUT_reg[7]_i_1}]
set_property LOC SLICE_X6Y159 [get_cells {OUT_reg[7]_i_1}]
set_property BEL D6LUT [get_cells {OUT_reg[8]_i_1}]
set_property LOC SLICE_X6Y158 [get_cells {OUT_reg[8]_i_1}]
set_property BEL C6LUT [get_cells {OUT_reg[9]_i_1}]
set_property LOC SLICE_X6Y158 [get_cells {OUT_reg[9]_i_1}]
set_property BEL B6LUT [get_cells {OUT_reg[10]_i_1}]
set_property LOC SLICE_X6Y158 [get_cells {OUT_reg[10]_i_1}]
set_property BEL A6LUT [get_cells {OUT_reg[11]_i_1}]
set_property LOC SLICE_X6Y158 [get_cells {OUT_reg[11]_i_1}]
set_property BEL D6LUT [get_cells {OUT_reg[12]_i_1}]
set_property LOC SLICE_X6Y157 [get_cells {OUT_reg[12]_i_1}]
set_property BEL C6LUT [get_cells {OUT_reg[13]_i_1}]
set_property LOC SLICE_X6Y157 [get_cells {OUT_reg[13]_i_1}]
set_property BEL B6LUT [get_cells {OUT_reg[14]_i_1}]
set_property LOC SLICE_X6Y157 [get_cells {OUT_reg[14]_i_1}]
set_property BEL A5LUT [get_cells {OUT_reg[15]_i_1}]
set_property LOC SLICE_X6Y157 [get_cells {OUT_reg[15]_i_1}]
set_property BEL A6LUT [get_cells {OUT_reg[15]_i_2}]
set_property LOC SLICE_X6Y157 [get_cells {OUT_reg[15]_i_2}]
set_property BEL DFF [get_cells {OUT_reg_reg[0]}]
set_property LOC SLICE_X6Y160 [get_cells {OUT_reg_reg[0]}]
set_property BEL CFF [get_cells {OUT_reg_reg[1]}]
set_property LOC SLICE_X6Y160 [get_cells {OUT_reg_reg[1]}]
set_property BEL BFF [get_cells {OUT_reg_reg[2]}]
set_property LOC SLICE_X6Y160 [get_cells {OUT_reg_reg[2]}]
set_property BEL AFF [get_cells {OUT_reg_reg[3]}]
set_property LOC SLICE_X6Y160 [get_cells {OUT_reg_reg[3]}]
set_property BEL D5FF [get_cells {OUT_reg_reg[4]}]
set_property LOC SLICE_X6Y159 [get_cells {OUT_reg_reg[4]}]
set_property BEL C5FF [get_cells {OUT_reg_reg[5]}]
set_property LOC SLICE_X6Y159 [get_cells {OUT_reg_reg[5]}]
set_property BEL B5FF [get_cells {OUT_reg_reg[6]}]
set_property LOC SLICE_X6Y159 [get_cells {OUT_reg_reg[6]}]
set_property BEL A5FF [get_cells {OUT_reg_reg[7]}]
set_property LOC SLICE_X6Y159 [get_cells {OUT_reg_reg[7]}]
set_property BEL D5FF [get_cells {OUT_reg_reg[8]}]
set_property LOC SLICE_X6Y158 [get_cells {OUT_reg_reg[8]}]
set_property BEL CFF [get_cells {OUT_reg_reg[9]}]
set_property LOC SLICE_X6Y158 [get_cells {OUT_reg_reg[9]}]
set_property BEL B5FF [get_cells {OUT_reg_reg[10]}]
set_property LOC SLICE_X6Y158 [get_cells {OUT_reg_reg[10]}]
set_property BEL AFF [get_cells {OUT_reg_reg[11]}]
set_property LOC SLICE_X6Y158 [get_cells {OUT_reg_reg[11]}]
set_property BEL B5FF [get_cells {OUT_reg_reg[14]}]
set_property LOC SLICE_X6Y157 [get_cells {OUT_reg_reg[14]}]

set_property BEL AFF [get_cells {OUT_reg_reg[15]}]
set_property LOC SLICE_X6Y157 [get_cells {OUT_reg_reg[15]}]
set_property BEL D5FF [get_cells {OUT_reg_reg[12]}]
set_property LOC SLICE_X6Y157 [get_cells {OUT_reg_reg[12]}]
set_property BEL CFF [get_cells {OUT_reg_reg[13]}]
set_property LOC SLICE_X6Y157 [get_cells {OUT_reg_reg[13]}]
set_property C_CLK_INPUT_FREQ_HZ 100000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
