## NX LAYOUT CONSTRAINTS 16-BIT PUF 002 -- STREAMLINED NET DELAYS & MID D-LATCH RANGE

## Clock signal
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk]
#set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk_lo]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
#create_clock -period 1000.000 -name sys_clk_pin -waveform {0.000 500.000} -add [get_ports clk_lo]


## Button signals
#set_property PACKAGE_PIN C12 [get_ports reset]
#set_property IOSTANDARD LVCMOS33 [get_ports reset]
#set_property PACKAGE_PIN M18 [get_ports START]
#set_property IOSTANDARD LVCMOS33 [get_ports START]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets StartN_IBUF]
set_property CLOCK_BUFFER_TYPE BUFG [get_ports reset]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets reset_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets START_IBUF]

##Switches
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports reset]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports START]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports {addr[0]}]
set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports rst_div]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports selclk]

##Pmod Header JB

#set_property -dict { PACKAGE_PIN D14   IOSTANDARD LVCMOS33 } [get_ports { JB[1] }]; #IO_L1P_T0_AD0P_15 Sch=jb[1]
#set_property -dict { PACKAGE_PIN H14   IOSTANDARD LVCMOS33 } [get_ports { JB[4] }]; #IO_L15P_T2_DQS_15 Sch=jb[4]
#set_property -dict { PACKAGE_PIN F13   IOSTANDARD LVCMOS33 } [get_ports { JB[8] }]; #IO_L5P_T0_AD9P_15 Sch=jb[8]
#set_property -dict { PACKAGE_PIN G13   IOSTANDARD LVCMOS33 } [get_ports { JB[9] }]; #IO_0_15 Sch=jb[9]
#set_property -dict { PACKAGE_PIN H16   IOSTANDARD LVCMOS33 } [get_ports { JB[10] }]; #IO_L13P_T2_MRCC_15 Sch=jb[10]


##Pmod Header JC
set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[0]}]
set_property -dict {PACKAGE_PIN F6 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[1]}]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[2]}]
set_property -dict {PACKAGE_PIN G6 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[3]}]
set_property -dict {PACKAGE_PIN E7 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[4]}]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[5]}]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[6]}]
set_property -dict {PACKAGE_PIN E6 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[7]}]

##Pmod Header JD
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[8]}]
set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[9]}]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[10]}]
set_property -dict {PACKAGE_PIN G3 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[11]}]
set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[12]}]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[13]}]
set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[14]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {OUT_reg[15]}]

## DD-Latch Nets
set_property BEL AFF [get_cells {puf_loop[0].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X33Y198 [get_cells {puf_loop[0].puf_inst/dl1/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[2].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X33Y196 [get_cells {puf_loop[2].puf_inst/dl1/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[3].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X31Y195 [get_cells {puf_loop[3].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[4].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X49Y178 [get_cells {puf_loop[4].puf_inst/dl1/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[5].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X47Y177 [get_cells {puf_loop[5].puf_inst/dl0/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[5].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X49Y177 [get_cells {puf_loop[5].puf_inst/dl1/Q_reg_i_1}]
set_property BEL AFF [get_cells {puf_loop[6].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X47Y176 [get_cells {puf_loop[6].puf_inst/dl0/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[7].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X49Y175 [get_cells {puf_loop[7].puf_inst/dl1/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[9].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X16Y177 [get_cells {puf_loop[9].puf_inst/dl1/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[9].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X14Y177 [get_cells {puf_loop[9].puf_inst/dl0/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[11].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X16Y175 [get_cells {puf_loop[11].puf_inst/dl1/Q_reg}]

set_property BEL A6LUT [get_cells {puf_loop[0].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X31Y198 [get_cells {puf_loop[0].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[0].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X31Y198 [get_cells {puf_loop[0].puf_inst/dl0/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[0].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X33Y198 [get_cells {puf_loop[0].puf_inst/dl1/Q_reg_i_1}]
set_property BEL A6LUT [get_cells {puf_loop[1].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X31Y197 [get_cells {puf_loop[1].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[1].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X31Y197 [get_cells {puf_loop[1].puf_inst/dl0/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[1].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X33Y197 [get_cells {puf_loop[1].puf_inst/dl1/Q_reg_i_1}]
set_property BEL AFF [get_cells {puf_loop[1].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X33Y197 [get_cells {puf_loop[1].puf_inst/dl1/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[2].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X31Y196 [get_cells {puf_loop[2].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[2].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X31Y196 [get_cells {puf_loop[2].puf_inst/dl0/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[2].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X33Y196 [get_cells {puf_loop[2].puf_inst/dl1/Q_reg_i_1}]
set_property BEL AFF [get_cells {puf_loop[3].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X31Y195 [get_cells {puf_loop[3].puf_inst/dl0/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[3].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X33Y195 [get_cells {puf_loop[3].puf_inst/dl1/Q_reg_i_1}]
set_property BEL AFF [get_cells {puf_loop[4].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X47Y178 [get_cells {puf_loop[4].puf_inst/dl0/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[4].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X49Y178 [get_cells {puf_loop[4].puf_inst/dl1/Q_reg_i_1}]
set_property BEL A6LUT [get_cells {puf_loop[4].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X47Y178 [get_cells {puf_loop[4].puf_inst/dl0/OUT_INST_0}]
set_property BEL A6LUT [get_cells {puf_loop[5].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X47Y177 [get_cells {puf_loop[5].puf_inst/dl0/OUT_INST_0}]
set_property BEL A6LUT [get_cells {puf_loop[6].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X49Y176 [get_cells {puf_loop[6].puf_inst/dl1/Q_reg_i_1}]
set_property BEL AFF [get_cells {puf_loop[6].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X49Y176 [get_cells {puf_loop[6].puf_inst/dl1/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[7].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X47Y175 [get_cells {puf_loop[7].puf_inst/dl0/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[7].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X49Y175 [get_cells {puf_loop[7].puf_inst/dl1/Q_reg_i_1}]
set_property BEL A6LUT [get_cells {puf_loop[7].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X47Y175 [get_cells {puf_loop[7].puf_inst/dl0/OUT_INST_0}]
set_property BEL A6LUT [get_cells {puf_loop[8].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X14Y178 [get_cells {puf_loop[8].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[8].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X14Y178 [get_cells {puf_loop[8].puf_inst/dl0/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[8].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X16Y178 [get_cells {puf_loop[8].puf_inst/dl1/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[8].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X16Y178 [get_cells {puf_loop[8].puf_inst/dl1/Q_reg_i_1}]
set_property BEL A6LUT [get_cells {puf_loop[9].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X14Y177 [get_cells {puf_loop[9].puf_inst/dl0/OUT_INST_0}]
set_property BEL A6LUT [get_cells {puf_loop[9].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X16Y177 [get_cells {puf_loop[9].puf_inst/dl1/Q_reg_i_1}]
set_property BEL A6LUT [get_cells {puf_loop[10].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X14Y176 [get_cells {puf_loop[10].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[10].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X14Y176 [get_cells {puf_loop[10].puf_inst/dl0/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[10].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X16Y176 [get_cells {puf_loop[10].puf_inst/dl1/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[10].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X16Y176 [get_cells {puf_loop[10].puf_inst/dl1/Q_reg_i_1}]
set_property BEL A6LUT [get_cells {puf_loop[11].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X16Y175 [get_cells {puf_loop[11].puf_inst/dl1/Q_reg_i_1}]
set_property BEL A6LUT [get_cells {puf_loop[11].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X14Y175 [get_cells {puf_loop[11].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[11].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X14Y175 [get_cells {puf_loop[11].puf_inst/dl0/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[12].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X32Y152 [get_cells {puf_loop[12].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[12].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X32Y152 [get_cells {puf_loop[12].puf_inst/dl0/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[12].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X34Y152 [get_cells {puf_loop[12].puf_inst/dl1/Q_reg_i_1}]
set_property BEL AFF [get_cells {puf_loop[12].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X34Y152 [get_cells {puf_loop[12].puf_inst/dl1/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[13].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X32Y151 [get_cells {puf_loop[13].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[13].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X32Y151 [get_cells {puf_loop[13].puf_inst/dl0/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[13].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X34Y151 [get_cells {puf_loop[13].puf_inst/dl1/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[13].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X34Y151 [get_cells {puf_loop[13].puf_inst/dl1/Q_reg_i_1}]
set_property BEL A6LUT [get_cells {puf_loop[14].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X32Y150 [get_cells {puf_loop[14].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[14].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X32Y150 [get_cells {puf_loop[14].puf_inst/dl0/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[14].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X34Y150 [get_cells {puf_loop[14].puf_inst/dl1/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[14].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X34Y150 [get_cells {puf_loop[14].puf_inst/dl1/Q_reg_i_1}]
set_property BEL A6LUT [get_cells {puf_loop[15].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X32Y149 [get_cells {puf_loop[15].puf_inst/dl0/OUT_INST_0}]
set_property BEL AFF [get_cells {puf_loop[15].puf_inst/dl0/Q_reg}]
set_property LOC SLICE_X32Y149 [get_cells {puf_loop[15].puf_inst/dl0/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[15].puf_inst/dl1/Q_reg_i_1}]
set_property LOC SLICE_X34Y149 [get_cells {puf_loop[15].puf_inst/dl1/Q_reg_i_1}]
set_property BEL AFF [get_cells {puf_loop[15].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X34Y149 [get_cells {puf_loop[15].puf_inst/dl1/Q_reg}]
set_property BEL AFF [get_cells {puf_loop[5].puf_inst/dl1/Q_reg}]
set_property LOC SLICE_X49Y177 [get_cells {puf_loop[5].puf_inst/dl1/Q_reg}]
set_property BEL A6LUT [get_cells {puf_loop[6].puf_inst/dl0/OUT_INST_0}]
set_property LOC SLICE_X47Y176 [get_cells {puf_loop[6].puf_inst/dl0/OUT_INST_0}]


set_property BEL CFF [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/uuid_stamp_reg[28]}]
set_property LOC SLICE_X45Y81 [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/uuid_stamp_reg[28]}]
set_property BEL B6LUT [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/reg_do[14]_i_2}]
set_property LOC SLICE_X44Y81 [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/reg_do[14]_i_2}]
set_property BEL DFF [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/uuid_stamp_reg[34]}]
set_property LOC SLICE_X45Y82 [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/uuid_stamp_reg[34]}]
set_property BEL AFF [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/uuid_stamp_reg[18]}]
set_property LOC SLICE_X44Y82 [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/uuid_stamp_reg[18]}]
set_property BEL BFF [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/uuid_stamp_reg[46]}]
set_property LOC SLICE_X44Y81 [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/uuid_stamp_reg[46]}]
set_property BEL A6LUT [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/reg_do[13]_i_3}]
set_property LOC SLICE_X44Y82 [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/reg_do[13]_i_3}]
set_property BEL A6LUT [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/reg_do[12]_i_2}]
set_property LOC SLICE_X44Y81 [get_cells {your_instance_name/inst/ila_core_inst/u_ila_regs/U_XSDB_SLAVE/reg_do[12]_i_2}]


